#!/bin/bash

set -euo pipefail

show_status() {
  [ ! -d "$1/.git" ] && return

  local ahead="$(
    (cd $1 && git status) |
      rg -i "ahead" |
      rg -io "[\d]+ commit[s]?" |
      rg -o "[\d]+"
  )"

  [ "$ahead" ] && ahead="+$ahead"
  printf "%7s %s\n" "$ahead" "$1"

  local modified="$(cd $1 && git status --short)"
  [ ! "$modified" ] && return

  local n="$(echo "$modified" | wc -l)"
  echo "$modified" |
    while read line; do
      local n="$(($n - 1))"
      [ "$n" -gt 0 ] && local p="├──" || local p="└──"
      printf "\t%s %s\n" "$p" "$line"
    done
}

for repo in $(ls -1d */); do
  show_status $repo
done
